# Generated by Django 5.0.7 on 2024-07-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diretor_produtora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('ano', models.IntegerField()),
                ('categoria', models.ManyToManyField(to='core.categoria')),
                ('diretor', models.ManyToManyField(to='core.diretor')),
                ('produtora', models.ManyToManyField(to='core.produtora')),
            ],
        ),
    ]
