# Generated by Django 5.0.7 on 2024-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('telefone', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='filme',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='produtora',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Diretor',
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.DeleteModel(
            name='Produtora',
        ),
    ]
