# Generated by Django 5.0.7 on 2024-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoa_remove_filme_categoria_remove_filme_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
