# Generated by Django 5.0.7 on 2024-07-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
    ]
